<?php

// Generated by Haxe 3.3.0
class haxe_io_Bytes {
	public function __construct($length, $b) {
		if(!php_Boot::$skip_constructor) {
		$this->length = $length;
		$this->b = $b;
	}}
	public $length;
	public $b;
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	static function ofString($s) {
		$x = new php__BytesData_Wrapper($s);
		$x1 = $x;
		$tmp = strlen($x1->s);
		return new haxe_io_Bytes($tmp, $x1);
	}
	function __toString() { return 'haxe.io.Bytes'; }
}
