<?php

// Generated by Haxe 3.3.0
class php_db__PDO_PHPNativeStrategy extends php_db__PDO_TypeStrategy {
	public function __construct() { if(!php_Boot::$skip_constructor) {
		parent::__construct();
	}}
	public function map($data) {
		$tmp = !isset($data["native_type"]);
		if($tmp) {
			$tmp1 = isset($data["precision"]);
			if($tmp1) {
				return "int";
			} else {
				return "string";
			}
		}
		$pdo_type_str = PDO::PARAM_STR;
		$pdo_type = $data["pdo_type"];
		$type = $data["native_type"];
		$type = strtolower($type);
		switch($type) {
		case "blob":{
			if($pdo_type === $pdo_type_str) {
				return "string";
			} else {
				return "blob";
			}
		}break;
		case "int":case "int24":case "int32":case "long":case "longlong":case "short":case "tiny":{
			return "int";
		}break;
		case "decimal":case "double":case "float":case "newdecimal":{
			return "float";
		}break;
		case "date":case "datetime":case "timestamp":{
			return "date";
		}break;
		case "bool":case "tinyint(1)":{
			return "bool";
		}break;
		default:{
			return "string";
		}break;
		}
	}
	function __toString() { return 'php.db._PDO.PHPNativeStrategy'; }
}
