<?php

// Generated by Haxe 3.3.0
class php_db__PDO_TypeStrategy {
	public function __construct() {}
	public function map($data) {
		throw new HException("must override");
	}
	static function convert($v, $type) {
		if($v === null) {
			return $v;
		}
		switch($type) {
		case "blob":{
			return haxe_io_Bytes::ofString($v);
		}break;
		case "bool":{
			return (bool)($v);
		}break;
		case "date":{
			return Date::fromString($v);
		}break;
		case "float":{
			return floatval($v);
		}break;
		case "int":{
			return intval($v);
		}break;
		default:{
			return $v;
		}break;
		}
	}
	function __toString() { return 'php.db._PDO.TypeStrategy'; }
}
