<?php

// Generated by Haxe 3.3.0
class ErrorMessage {
	public function __construct(){}
	static $NO_MODE = "Error: No mode";
	static $NO_PROP = "Error: Not enough properties ";
	static $INVALID_TERM = "Error: Invalid Term";
	function __toString() { return 'ErrorMessage'; }
}
