<?php

// Generated by Haxe 3.3.0
class Main {
	public function __construct(){}
	static function main() {
		$tmp = php_Web::getParams();
		$tmp1 = db_DBManager::getResults($tmp);
		php_Lib::hprint($tmp1);
	}
	function __toString() { return 'Main'; }
}
