<?php

// Generated by Haxe 3.3.0
class sys_io_File {
	public function __construct(){}
	static function saveContent($path, $content) {
		file_put_contents($path, $content);
	}
	function __toString() { return 'sys.io.File'; }
}
